### ISSUE TITLE
Upgrade to newer .NET framework

### ISSUE THREAD

**Issue by kontext-e** [softvis-research/jqa-csharp-plugin#1]
When running "dotnet .\roslyn\CSharpSyntaxToXML.dll <CS File>",  framework 'Microsoft.NETCore.App', version '2.2.0' was not found. Installation from https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.2.0&arch=x64&rid=win10-x64 is not possible anymore because this release has reached end of life, meaning it is no longer supported. It is recommended moving to a supported release, such as .NET Core 3.1 Runtime.

**Comment by b-pos465** [comment]
Please have a look at the [new version of the C# plugin](https://github.com/softvis-research/jqa-csharp-plugin/releases/tag/v0.1.2-alpha) which is built with .NET 5. It is tested on Windows (manually while developing) and Linux via [Travis CI](https://travis-ci.com/github/softvis-research/jqa-csharp-plugin). The current graph model can be found in the [README.md](https://github.com/softvis-research/jqa-csharp-plugin).
